/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-focus': 'var(--color-primary-focus)',
        ink: 'var(--color-ink)',
        'ink-muted': 'var(--color-ink-muted)',
        'ink-subtle': 'var(--color-ink-subtle)',
        'ink-tertiary': 'var(--color-ink-tertiary)',
        canvas: 'var(--color-canvas)',
        'surface-1': 'var(--color-surface-1)',
        'surface-2': 'var(--color-surface-2)',
        'surface-3': 'var(--color-surface-3)',
        'surface-4': 'var(--color-surface-4)',
        hairline: 'var(--color-hairline)',
        'hairline-strong': 'var(--color-hairline-strong)',
        'hairline-tertiary': 'var(--color-hairline-tertiary)',
        'inverse-canvas': 'var(--color-inverse-canvas)',
        'inverse-surface-1': 'var(--color-inverse-surface-1)',
        'inverse-surface-2': 'var(--color-inverse-surface-2)',
        'inverse-ink': 'var(--color-inverse-ink)',
        'brand-secure': 'var(--color-brand-secure)',
        'semantic-success': 'var(--color-semantic-success)',
        'semantic-overlay': 'var(--color-semantic-overlay)',
      },
      fontFamily: {
        display: ['"Linear Display"', '"SF Pro Display"', 'Inter', 'sans-serif'],
        text: ['"Linear Text"', '"SF Pro Display"', 'Inter', 'sans-serif'],
        mono: ['"Linear Mono"', 'ui-monospace', '"SF Mono"', 'Menlo', '"JetBrains Mono"', 'monospace'],
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '96px',
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'xxl': '24px',
        'pill': '9999px',
        'full': '9999px',
      },
      letterSpacing: {
        'display-xl': '-3.0px',
        'display-lg': '-1.8px',
        'display-md': '-1.0px',
        'headline': '-0.6px',
        'card-title': '-0.4px',
        'subhead': '-0.2px',
        'body-lg': '-0.1px',
        'body': '-0.05px',
        'eyebrow': '0.4px',
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.05', fontWeight: '600', letterSpacing: '-3.0px' }],
        'display-lg': ['56px', { lineHeight: '1.10', fontWeight: '600', letterSpacing: '-1.8px' }],
        'display-md': ['40px', { lineHeight: '1.15', fontWeight: '600', letterSpacing: '-1.0px' }],
        'headline': ['28px', { lineHeight: '1.20', fontWeight: '600', letterSpacing: '-0.6px' }],
        'card-title': ['22px', { lineHeight: '1.25', fontWeight: '500', letterSpacing: '-0.4px' }],
        'subhead': ['20px', { lineHeight: '1.40', fontWeight: '400', letterSpacing: '-0.2px' }],
        'body-lg': ['18px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '-0.1px' }],
        'body': ['16px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '-0.05px' }],
        'body-sm': ['14px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '0' }],
        'caption': ['12px', { lineHeight: '1.40', fontWeight: '400', letterSpacing: '0' }],
        'button': ['14px', { lineHeight: '1.20', fontWeight: '500', letterSpacing: '0' }],
        'eyebrow': ['13px', { lineHeight: '1.30', fontWeight: '500', letterSpacing: '0.4px' }],
        'mono': ['13px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '0' }],
      },
      boxShadow: {
        'none': 'none',
      }
    },
  },
  plugins: [],
}
